name: Instagram to Airtable (ScrapeCreators)

on:
  schedule:
    - cron: '0 */8 * * *' # every 8 hours
  workflow_dispatch:

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install requests pyairtable
      - name: Run ScrapeCreators script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          BASE_ID: ${{ secrets.BASE_ID }}
          SCRAPECREATORS_API_KEY: ${{ secrets.SCRAPECREATORS_API_KEY }}
        run: python scrapecreators_fetch_and_update.py